// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// FORCE load .env for Prisma CLI (Windows-safe)
dotenv.config({
  path: path.resolve(process.cwd(), ".env"),
});

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
  },

  datasource: {
    // prisma migrate dev REQUIRES a concrete URL here
    url: process.env.DIRECT_URL!,
  },
});
